package com.zhyrBlog.model.pojo;

public class BlogUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.id
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.userName
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.password
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.id
     *
     * @return the value of blog_user.id
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.id
     *
     * @param id the value for blog_user.id
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.userName
     *
     * @return the value of blog_user.userName
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.userName
     *
     * @param username the value for blog_user.userName
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.password
     *
     * @return the value of blog_user.password
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.password
     *
     * @param password the value for blog_user.password
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }
}