package com.zhyrBlog.model.mapper;

import com.zhyrBlog.model.pojo.BlogUser;
import com.zhyrBlog.model.pojo.BlogUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BlogUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    int countByExample(BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    int deleteByExample(BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    @Delete({
        "delete from blog_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    @Insert({
        "insert into blog_user (id, userName, ",
        "password)",
        "values (#{id,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR})"
    })
    int insert(BlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    int insertSelective(BlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    List<BlogUser> selectByExample(BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    @Select({
        "select",
        "id, userName, password",
        "from blog_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    BlogUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    int updateByExampleSelective(@Param("record") BlogUser record, @Param("example") BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    int updateByExample(@Param("record") BlogUser record, @Param("example") BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    int updateByPrimaryKeySelective(BlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Tue Jun 09 13:02:21 CST 2015
     */
    @Update({
        "update blog_user",
        "set userName = #{username,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BlogUser record);
}